
package service_now.ivr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceNowSoap", targetNamespace = "http://www.service-now.com/IVR")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceNowSoap {


    /**
     * 
     * @param caller
     * @param shortDescription
     * @param subcategory
     * @param description
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.service-now.com/IVR/execute")
    @WebResult(name = "number", targetNamespace = "http://www.service-now.com/IVR")
    @RequestWrapper(localName = "execute", targetNamespace = "http://www.service-now.com/IVR", className = "com.service_now.ivr.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://www.service-now.com/IVR", className = "com.service_now.ivr.ExecuteResponse")
    public String execute(
        @WebParam(name = "shortDescription", targetNamespace = "http://www.service-now.com/IVR")
        String shortDescription,
        @WebParam(name = "description", targetNamespace = "http://www.service-now.com/IVR")
        String description,
        @WebParam(name = "caller", targetNamespace = "http://www.service-now.com/IVR")
        String caller,
        @WebParam(name = "subcategory", targetNamespace = "http://www.service-now.com/IVR")
        String subcategory);

}
