
package service_now.ivr;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceNow_IVR", targetNamespace = "http://www.service-now.com/IVR", wsdlLocation = "https://ouptest.service-now.com/IVR.do?WSDL")
public class ServiceNowIVR
    extends Service
{

    private final static URL SERVICENOWIVR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(service_now.ivr.ServiceNowIVR.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = service_now.ivr.ServiceNowIVR.class.getResource(".");
            url = new URL(baseUrl, "https://ouptest.service-now.com/IVR.do?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ouptest.service-now.com/IVR.do?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICENOWIVR_WSDL_LOCATION = url;
    }

    public ServiceNowIVR(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceNowIVR() {
        super(SERVICENOWIVR_WSDL_LOCATION, new QName("http://www.service-now.com/IVR", "ServiceNow_IVR"));
    }

    /**
     * 
     * @return
     *     returns ServiceNowSoap
     */
    @WebEndpoint(name = "ServiceNowSoap")
    public ServiceNowSoap getServiceNowSoap() {
        return super.getPort(new QName("http://www.service-now.com/IVR", "ServiceNowSoap"), ServiceNowSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceNowSoap
     */
    @WebEndpoint(name = "ServiceNowSoap")
    public ServiceNowSoap getServiceNowSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.service-now.com/IVR", "ServiceNowSoap"), ServiceNowSoap.class, features);
    }

}
